# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locater', '0004_auto_20180109_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacentre',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
